#!/bin/bash

main() {
    case $1 in 
        begin) begin;;
        update) update;;
        help) help;;
    esac
}

#Start new repo, connect to remote
begin() {
    #set up dir
    read -p "Enter Repo Name: " repo_name

    echo -------------------
    echo "  Adding directory"
    echo -------------------
    mkdir $repo_name

    cd $repo_name

    echo -------------------
    echo      git init
    echo -------------------
    git init

    echo -------------------
    echo "   Adding README"
    echo -------------------
    > README.md

    echo -------------------
    echo " Adding .gitignore"
    echo -------------------
    > .gitingnore

    #join to repo
    read -p "Enter Remote Repo Address: " repo_address
    echo ----------------------
    echo " git remote add origin"
    echo ----------------------
    git remote add origin $repo_address

    echo -------------------
    echo Staging all changes
    echo -------------------
    git add .

    echo -----------------------
    echo " Making initial commit"
    echo -----------------------
    git commit -m "Initial Commit" 

    echo -------------------------
    echo git push -u origin master
    echo -------------------------
    git push -u origin master
}

update() {
    echo -------------------
    echo Staging all changes
    echo -------------------
    git add .
    git status

    get current branch
    current_branch=$(git branch | grep \* | cut -d ' ' -f2)
    echo -------------------------
    echo " Current Branch: $current_branch"
    echo -------------------------

    read -p "Enter commit message: " commit_message
    echo -------------------------
    echo "   Committing changes"
    echo -------------------------
    git commit -m "$commit_message"

    read -p "Do you wish to push to the current branch? y/n: " push_decision
    if [ "$push_decision" == "y" ]
    then
        echo ---------------------
        echo " Pushing changes"
        echo ---------------------
        git push origin $current_branch
    fi
}

help () {
    echo "Available commands:

begin 

- will add new dir at current location along with git init, README, and .gitignore and make an initial commit to supplied repo

update

- will stage all changes, commit these with given message, give user option to push or not"
}

main "$@"